/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TouristInfoRouteImport } from './routes/tourist-info'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedBrowseRouteImport } from './routes/_authenticated.browse'
import { Route as AuthenticatedPlacePlaceIdRouteImport } from './routes/_authenticated.place.$placeId'

const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristInfoRoute = TouristInfoRouteImport.update({
  id: '/tourist-info',
  path: '/tourist-info',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrowseRoute = AuthenticatedBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlacePlaceIdRoute =
  AuthenticatedPlacePlaceIdRouteImport.update({
    id: '/place/$placeId',
    path: '/place/$placeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/emergency': typeof EmergencyRoute
  '/tourist-info': typeof TouristInfoRoute
  '/transport': typeof TransportRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/place/$placeId': typeof AuthenticatedPlacePlaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/emergency': typeof EmergencyRoute
  '/tourist-info': typeof TouristInfoRoute
  '/transport': typeof TransportRoute
  '/browse': typeof AuthenticatedBrowseRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/place/$placeId': typeof AuthenticatedPlacePlaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/emergency': typeof EmergencyRoute
  '/tourist-info': typeof TouristInfoRoute
  '/transport': typeof TransportRoute
  '/_authenticated/browse': typeof AuthenticatedBrowseRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/place/$placeId': typeof AuthenticatedPlacePlaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/emergency'
    | '/tourist-info'
    | '/transport'
    | '/browse'
    | '/profile'
    | '/place/$placeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/emergency'
    | '/tourist-info'
    | '/transport'
    | '/browse'
    | '/profile'
    | '/place/$placeId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/emergency'
    | '/tourist-info'
    | '/transport'
    | '/_authenticated/browse'
    | '/_authenticated/profile'
    | '/_authenticated/place/$placeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  EmergencyRoute: typeof EmergencyRoute
  TouristInfoRoute: typeof TouristInfoRoute
  TransportRoute: typeof TransportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist-info': {
      id: '/tourist-info'
      path: '/tourist-info'
      fullPath: '/tourist-info'
      preLoaderRoute: typeof TouristInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/browse': {
      id: '/_authenticated/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AuthenticatedBrowseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/place/$placeId': {
      id: '/_authenticated/place/$placeId'
      path: '/place/$placeId'
      fullPath: '/place/$placeId'
      preLoaderRoute: typeof AuthenticatedPlacePlaceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBrowseRoute: typeof AuthenticatedBrowseRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPlacePlaceIdRoute: typeof AuthenticatedPlacePlaceIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBrowseRoute: AuthenticatedBrowseRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPlacePlaceIdRoute: AuthenticatedPlacePlaceIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  EmergencyRoute: EmergencyRoute,
  TouristInfoRoute: TouristInfoRoute,
  TransportRoute: TransportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
